NN Creating & Layers frontend
hse-mentorship/nnbuilder pull request #21
Opened 2022-05-20 11:16 UTC by ancharts

2022-06-16 12:30 UTC, AnastasiiaGorelova approved these changes

2022-06-16 16:18 UTC, iskhakovt requested changes
Well there needs to be a code review, I guess?

2022-06-26 11:56 UTC, zerts commented on frontend/src/components/Editor.tsx
> +function Editor(props: EditorProps): JSX.Element {
JSX.Element можно не писать - это автоматически понятно линтеру)
Тут имеет смысл описывать выходной тип только тогда, когда есть всякие разные варианты выходных данных

2022-06-26 11:57 UTC, zerts commented on frontend/src/components/Editor.tsx
> +function Editor(props: EditorProps): JSX.Element {
Удобно разыменовывать параметры, чтобы не писать props. много раз
`Пишется так function Editor({ prop1, prop2, prop3 }: EditorProps): JSX.Element {`

2022-06-26 11:59 UTC, zerts commented on frontend/src/components/EditorWindow.tsx
> +    const edges = calculateEdges(layers)
сложные вычисления лучше оборачивать в useMemo, чтобы они не высчитывались на каждый рендер
`const edges = useMemo(() => calculateEdges(layers), [layers])`
Этот хук запоминает (мемоизирует) результат выполнения функции и возвращает тот же, если зависимости хука не поменялись

2022-06-26 11:59 UTC, zerts commented on frontend/src/components/EditorWindow.tsx
> +        return 200 + (800 - 200) * layerData.neurons.length / 100 //(Math.atan(layerData.neurons.length/100)) * 200 + 100
Наверно, такие константы приятно будет вынести и назвать)

2022-06-26 12:01 UTC, zerts commented on frontend/src/components/EditorWindow.tsx
> +    function add(n: number = 1) {
Такие внутренние функции лучше оборачивать в useCallback - хук аналогичен useMemo, только мемоизирует функцию, а не результат функции. Таким образом эти функции не пересоздаются на каждый рендер (актуально для всяких сложных/долгих функций)

2022-06-26 12:03 UTC, zerts commented on frontend/src/components/EditorWindow.tsx
> +        setLayers([new LayerData(0)])
Наверно, можно new LayerData(0) можно передать в useState, как initial value

2022-06-26 12:03 UTC, zerts commented on frontend/src/components/EditorWindow.tsx
> +            <div className={"layers-with-settings"}>
Если значение аргумента у тэга - обычная строка, то можно его указывать без скобок
`<div className="layers-with-settings">`

2022-06-26 12:05 UTC, zerts commented on frontend/src/components/Header.tsx
> +export default Header
export default - это интересная история, но для обычных компонентов можно писать и без неё.
Так можно будет напрямую импортить компоненты
+
export default добавляют лишние вычисления, так как исполняет функцию при экспроте
Но это больше вкусовщина)

2022-06-26 12:08 UTC, zerts commented on frontend/src/index.tsx
> +        <App authService={api.authService} modificationService={api.modificationService} taskQueueService={api.taskQueueService} versionService={api.versionService} userAccountService = {api.userAcco
можно добавить переносы строки тут по комментам))

2022-06-26 12:09 UTC, zerts commented
Хорошая работа!

2022-06-26 12:13 UTC, zerts commented on frontend/src/components/Header.tsx
> +                {user == '' ? <><Link to='/register'>Register</Link>
Я бы тут добавил переносов строк

2022-06-28 18:14 UTC, iskhakovt approved these changes
Unblocking

2022-06-28 18:57 UTC, merged